include(
  /Users/sarathmenon/Documents/eth_projects/freertos_sim/crazyflie-firmware/cmake/gcc-arm-none-eabi.cmake
)
include(
  /Users/sarathmenon/Documents/eth_projects/freertos_sim/crazyflie-firmware/cmake/board.cmake
)
include(
  /Users/sarathmenon/Documents/eth_projects/freertos_sim/crazyflie-firmware/cmake/cf2.cmake
)
